# Cargo configuration for htmlens-worker WASM build

[build]
target = "wasm32-unknown-unknown"

# Configure getrandom for WASM target
# getrandom 0.3 requires explicit configuration for wasm32-unknown-unknown
[target.wasm32-unknown-unknown]
rustflags = ["--cfg", "getrandom_backend=\"wasm_js\""]
